### ISSUE TITLE
Long messages issue

### ISSUE THREAD

**Issue by Tcheslavie** [nchizhov/DINSTAR-DWG-PYTHON-D#6]
Hello! 
There's a bit of a problem with the script. If there's a long sms received by a gate, it won't be deleted because the script doesn't send a response message. A gate will continue sending it to the script over and over again. 
More over, there's a python exception (lines might be different):
`Exception in thread Thread-53:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/home/DINSTAR-DWG-PYTHON-D-master/dwgc.py", line 142, in pingDWG
    self.sendDWG(self.create_header(), sdata)
  File "/home/DINSTAR-DWG-PYTHON-D-master/dwgc.py", line 159, in sendDWG
    self.conn.send(pkt)
  File "/usr/local/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor`

**Comment by nchizhov** [comment]
Hello.

May you show debug output from script?

**Comment by Tcheslavie** [comment]
I'm sorry, it was my mistake. It works like charm actually! Thank you.
